using function with local variable scope for any .profile or .bashrc action to prevent exposed variables in user shell

diff --git a/.bashrc.d/linux-gnu/bash_completion b/.bashrc.d/linux-gnu/bash_completion
--- a/.bashrc.d/linux-gnu/bash_completion
+++ b/.bashrc.d/linux-gnu/bash_completion
@@ -1,18 +1,23 @@
+#!/usr/bin/env bash
 # enable bash completion in interactive shells
-if ! shopt -oq posix; then
-  if [ -f /usr/share/bash-completion/bash_completion ]; then
-    bc_cmd=/usr/share/bash-completion/bash_completion
-  elif [ -f /etc/bash_completion ]; then
-    bc_cmd=/etc/bash_completion
-  fi
-fi
+loadBashCompletions() {
+    local bc_cmd
+    local bc_extension
+    if ! shopt -oq posix; then
+      if [ -f /usr/share/bash-completion/bash_completion ]; then
+        bc_cmd=/usr/share/bash-completion/bash_completion
+      elif [ -f /etc/bash_completion ]; then
+        bc_cmd=/etc/bash_completion
+      fi
+    fi
 
-if [ -f "$bc_cmd" ]; then
-    . ~/.bashrc.d/helper/sourceCompletions.sh "bash_completion" $bc_cmd
-else
-    echo -e $RED"--- bash_completion missing"$NO_COLOR
-    return 1
-fi
+    if [ -f "$bc_cmd" ]; then
+        . ~/.bashrc.d/helper/sourceCompletions.sh "bash_completion" $bc_cmd
+    else
+        echo -e $RED"--- bash_completion missing"$NO_COLOR
+        return 1
+    fi
 
-
-[ -d ~/.bashrc.d/__${BASH_SOURCE##*/} ] && . ~/.bashrc.d/helper/sourceCompletions.sh "bash_completion extensions" ~/.bashrc.d/__${BASH_SOURCE##*/}/*
+    [ -d ~/.bashrc.d/__${BASH_SOURCE##*/} ] && for bc_extension in ~/.bashrc.d/__${BASH_SOURCE##*/}/*; do . ~/.bashrc.d/helper/sourceCompletions.sh "__bash_completion_extension_$(basename $bc_extension)" ${bc_extension}; done
+}
+loadBashCompletions
